/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import { useEffect, useState } from 'react';

interface UserApp {
  status: string;
  firstName: string;
  lastName: string;
  resume: string;
}


const UserQRDetail: NextPage = () => {
  const { query: { uid } } = useRouter();
  const [app, changeApp] = useState<undefined | UserApp>(undefined);
  const [error, changeError] = useState("");

  useEffect(() => {
    fetch(`/apply/application/byuser/${uid}`).then(res => res.json()).then(data => changeApp(data)).catch((e) => {
      console.error(e);
      changeError("Couldn't find your TAMU Datathon Application, contact an organizer")
    })
  }, [uid, changeApp, changeError]);


  return (
    <div>
      <Head>
        <title>Your QR Code | TAMU Datathon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ margin: "1.5rem" }}>
        <p><a href="https://tamudatathon.com">🏠&nbsp;&nbsp;TAMU Datathon Homepage</a></p>
      </div>
      <div style={{ textAlign: "center", margin: "1.5rem" }}>
        {app?.status === "C" && (
          <>
            <img 
              src={`/qr/api/${uid}`}
              style={{ width: "100%", height: "100%", maxWidth: "300px", maxHeight: "300px", imageRendering: "pixelated" }}
              alt=""
            />
            <h2>{app?.firstName} {app?.lastName}</h2>
            <p>Admitted into TAMU Datathon 2021</p>
          </>
        )}
        {app?.status !== "C" && app?.firstName && (
          <>
            <p>It looks like this account is not addmitted to TAMU Datathon 2021. Did you login with the right account? Also, make sure you RSVP&apos;d in the <a href="/apply">application portal</a>.</p>
            <p><a href="/auth/login?r=/qr">Login with a different account</a></p>
          </>
        )}
        {app && !app?.status && !app?.firstName && !app?.lastName && (
          <>
            <p className="text-red">We couldn&apos;t find your application to TAMU Datathon 2021. Please check with an organizer for assistance.</p>
          </>
        )}
        {error && (
          <>
            <p className="text-red">{error}</p>
          </>
        )}
        {!app && (
          <p>Loading</p>
        )}
      </div>
    </div>
  )
}

export default UserQRDetail;
